from typing import Any

class EpubItem:
    id: str
    file_name: str
    def get_name(self) -> str: ...
    def get_id(self) -> str: ...
    def get_content(self, default: Any = ...) -> bytes: ...
    def set_content(self, content: bytes | str) -> None: ...

class EpubBook:
    spine: list[tuple[str, bool]]
    items: list[EpubItem]
    toc: list[Any]
    def get_items(self) -> list[EpubItem]: ...
    def get_items_of_type(self, item_type: int) -> list[EpubItem]: ...
    def add_item(self, item: EpubItem) -> EpubItem: ...

class EpubNav(EpubItem): ...
class EpubHtml(EpubItem): ...
class EpubImage(EpubItem): ...

class Link:
    title: str
    href: str
    content: list[Link] | None

class Section: ...

def read_epub(name: str, options: Any = ...) -> EpubBook: ...
def write_epub(name: str, book: EpubBook, options: Any = ...) -> bool: ...
